= Zemian notes on pgjdbc dev

= JDBC how connection is made

org.postgresql.Driver
    makeConnection()
        PgConnection()
            ConnectionFactoryImpl.openConnectionImpl() -> QueryExecutor
                enableSSL(PGStream) // Send SSL request packet if enabled
                sendStartupPacket(PGStream) // Send the startup message
                doAuthentication(PGStream) // Send password if needed
                QueryExecutorImpl(PGStream) // readStartupMessages() - receive ReadyForQuery message

                then query sent will be process by QueryExecutorImpl.processResults()


= Setup PostgreSQL on Windows without admin rights

1. Download zip version of Windows binaries
2. Start server by running
	bin/pg_ctl -D data init
	bin/pg_ctl -D data -l logs/posgres.log start
* Above will create default database with Windows current user. You need
to setup 'postgres' user manually.	
3. Manually create postgres user/role
	bin/createuser -s --replication postgres
	bin/createdb -U postgres postgres
	bin/psql postgres
	postgres=# alter role postgres with bypassrls;
	

= Setup pgjdbc tests with postgres 9.6

The https://jdbc.postgresql.org/development/development.html
notes are outdated. Use the following instead.

bin\createuser -d test -P
bin\createdb -E UTF8 -T template0 -U test test
bin\createlang plpgsql test

= pgjdbc tips

== Faster connection startup properties

assumeMinServerVersion=9.0

NOTE: the version must be major.minor format, or else it will auto fallback to "0"!
